export const ALL_SETTINGS = 'ALL_SETTINGS'
export const ALL_SETTINGS_SUCCESS = 'ALL_SETTINGS_SUCCESS'
export const ALL_SETTINGS_FAILURE = 'ALL_SETTINGS_FAILURE'

export const SETTINGS_BY_ID = 'SETTINGS_BY_ID'
export const SETTINGS_BY_ID_SUCCESS = 'SETTINGS_BY_ID_SUCCESS'
export const SETTINGS_BY_ID_FAILURE = "SETTINGS_BY_ID_FAILURE"

export const ADD_SETTINGS = 'ADD_SETTINGS'
export const ADD_SETTINGS_SUCCESS = 'ADD_SETTINGS_SUCCESS'
export const ADD_SETTINGS_FAILURE = 'ADD_SETTINGS_FAILURE'

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS'
export const UPDATE_SETTINGS_FAILURE = 'UPDATE_SETTINGS_FAILURE'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
