export const ALL_SUPPORT = 'ALL_SUPPORT'
export const ALL_SUPPORT_SUCCESS = 'ALL_SUPPORT_SUCCESS'
export const ALL_SUPPORT_FAILURE = 'ALL_SUPPORT_FAILURE'

export const SUPPORT_BY_ID = 'SUPPORT_BY_ID'
export const SUPPORT_BY_ID_SUCCESS = 'SUPPORT_BY_ID_SUCCESS'
export const SUPPORT_BY_ID_FAILURE = "SUPPORT_BY_ID_FAILURE"

export const ADD_SUPPORT = 'ADD_SUPPORT'
export const ADD_SUPPORT_SUCCESS = 'ADD_SUPPORT_SUCCESS'
export const ADD_SUPPORT_FAILURE = 'ADD_SUPPORT_FAILURE'

export const UPDATE_SUPPORT = 'UPDATE_SUPPORT'
export const UPDATE_SUPPORT_SUCCESS = 'UPDATE_SUPPORT_SUCCESS'
export const UPDATE_SUPPORT_FAILURE = 'UPDATE_SUPPORT_FAILURE'


export const ALL_PRIORITIES = "ALL_PRIORITIES"
export const ALL_PRIORITIES_SUCCESS = "ALL_PRIORITIES_SUCCESS"
export const ALL_PRIORITIES_FAILURE = "ALL_PRIORITIES_FAILURE"

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
