export const ALL_ORDER = 'ALL_ORDER'
export const ALL_ORDER_SUCCESS = 'ALL_ORDER_SUCCESS'
export const ALL_ORDER_FAILURE = 'ALL_ORDER_FAILURE'

export const ORDER_BY_ID = 'ORDER_BY_ID'
export const ORDER_BY_ID_SUCCESS = 'ORDER_BY_ID_SUCCESS'
export const ORDER_BY_ID_FAILURE = "ORDER_BY_ID_FAILURE"

export const ADD_ORDER = 'ADD_ORDER'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAILURE = 'ADD_ORDER_FAILURE'

export const UPDATE_ORDER = 'UPDATE_ORDER'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE'

export const REMOVE_ORDER = 'REMOVE_ORDER'
export const REMOVE_ORDER_SUCCESS = 'REMOVE_ORDER_SUCCESS'
export const REMOVE_ORDER_FAILURE = 'REMOVE_ORDER_FAILURE'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
