export const ALL_CLASS = 'ALL_CLASS'
export const ALL_CLASS_SUCCESS = 'ALL_CLASS_SUCCESS'
export const ALL_CLASS_FAILURE = 'ALL_CLASS_FAILURE'

export const CLASS_BY_ID = 'CLASS_BY_ID'
export const CLASS_BY_ID_SUCCESS = 'CLASS_BY_ID_SUCCESS'
export const CLASS_BY_ID_FAILURE = "CLASS_BY_ID_FAILURE"

export const ADD_CLASS = 'ADD_CLASS'
export const ADD_CLASS_SUCCESS = 'ADD_CLASS_SUCCESS'
export const ADD_CLASS_FAILURE = 'ADD_CLASS_FAILURE'

export const UPDATE_CLASS = 'UPDATE_CLASS'
export const UPDATE_CLASS_SUCCESS = 'UPDATE_CLASS_SUCCESS'
export const UPDATE_CLASS_FAILURE = 'UPDATE_CLASS_FAILURE'

export const REMOVE_CLASS = 'REMOVE_CLASS'
export const REMOVE_CLASS_SUCCESS = 'REMOVE_CLASS_SUCCESS'
export const REMOVE_CLASS_FAILURE = 'REMOVE_CLASS_FAILURE'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
