export const ALL_CATEGORYS = 'ALL_CATEGORYS'
export const ALL_CATEGORYS_SUCCESS = 'ALL_CATEGORYS_SUCCESS'
export const ALL_CATEGORYS_FAILURE = 'ALL_CATEGORYS_FAILURE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const CATEGORY_BY_ID = 'CATEGORY_BY_ID'
export const CATEGORY_BY_ID_SUCCESS = 'CATEGORY_BY_ID_SUCCESS'
export const CATEGORY_BY_ID_FAILURE = "CATEGORY_BY_ID_FAILURE"

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE'

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAILURE = 'UPDATE_CATEGORY_FAILURE'

export const REMOVE_CATEGORY = 'REMOVE_CATEGORY'
export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS'
export const REMOVE_CATEGORY_FAILURE = 'REMOVE_CATEGORY_FAILURE'

export const ALL_CATEGORYS_QUESTION_FAILURE = 'ALL_CATEGORYS_QUESTION_FAILURE'
export const ALL_CATEGORYS_QUESTION_SUCCESS = 'ALL_CATEGORYS_QUESTION_SUCCESS'
export const ALL_CATEGORYS_QUESTION = 'ALL_CATEGORYS_QUESTION'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
