export const ALL_QUESTIONS = 'ALL_QUESTIONS'
export const ALL_QUESTIONS_SUCCESS = 'ALL_QUESTIONS_SUCCESS'
export const ALL_QUESTIONS_FAILURE = 'ALL_QUESTIONS_FAILURE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const QUESTION_BY_ID = 'QUESTION_BY_ID'
export const QUESTION_BY_ID_SUCCESS = 'QUESTION_BY_ID_SUCCESS'
export const QUESTION_BY_ID_FAILURE = "QUESTION_BY_ID_FAILURE"

export const ADD_QUESTION = 'ADD_QUESTION'
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS'
export const ADD_QUESTION_FAILURE = 'ADD_QUESTION_FAILURE'

export const UPDATE_QUESTION = 'UPDATE_QUESTION'
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS'
export const UPDATE_QUESTION_FAILURE = 'UPDATE_QUESTION_FAILURE'

export const REMOVE_QUESTION = 'REMOVE_QUESTION'
export const REMOVE_QUESTION_SUCCESS = 'REMOVE_QUESTION_SUCCESS'
export const REMOVE_QUESTION_FAILURE = 'REMOVE_QUESTION_FAILURE'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
