export const ALL_SUBCATEGORIES = 'ALL_SUBCATEGORIES'
export const ALL_SUBCATEGORIES_SUCCESS = 'ALL_SUBCATEGORIES_SUCCESS'
export const ALL_SUBCATEGORIES_FAILURE = 'ALL_SUBCATEGORIES_FAILURE'

export const SUBCATEGORY_BY_ID = 'SUBCATEGORY_BY_ID'
export const SUBCATEGORY_BY_ID_SUCCESS = 'SUBCATEGORY_BY_ID_SUCCESS'
export const SUBCATEGORY_BY_ID_FAILURE = "SUBCATEGORY_BY_ID_FAILURE"

export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY'
export const ADD_SUBCATEGORY_SUCCESS = 'ADD_SUBCATEGORY_SUCCESS'
export const ADD_SUBCATEGORY_FAILURE = 'ADD_SUBCATEGORY_FAILURE'

export const UPDATE_SUBCATEGORY = 'UPDATE_SUBCATEGORY'
export const UPDATE_SUBCATEGORY_SUCCESS = 'UPDATE_SUBCATEGORY_SUCCESS'
export const UPDATE_SUBCATEGORY_FAILURE = 'UPDATE_SUBCATEGORY_FAILURE'

export const REMOVE_SUBCATEGORY = 'REMOVE_SUBCATEGORY'
export const REMOVE_SUBCATEGORY_SUCCESS = 'REMOVE_SUBCATEGORY_SUCCESS'
export const REMOVE_SUBCATEGORY_FAILURE = 'REMOVE_SUBCATEGORY_FAILURE'

export const ERROR_MSG = 'ERROR_MSG'
export const SUCCESS_MSG = 'SUCCESS_MSG'
